scalar DateTime

type User {
  id: ID!
  name: String!
  email: String!
  startDate: DateTime
}

type Query {
  getUsers: [User!]
}

type Mutation {
  createUser(input:CreateUserInput) : Boolean
}

input CreateUserInput {
  id: ID!
  name: String!
  email: String!
  startDate: DateTime
}